%SW_LOG_JOB_INFO% --message="Configuring libxml2..."

cmake^
 -B %SW_XML2_BUILD_DIR%^
 -D BUILD_SHARED_LIBS=NO^
 -D CMAKE_BUILD_TYPE=Release^
 -D CMAKE_C_COMPLER=cl^
 -D CMAKE_C_FLAGS="/GS- /Oy /Gw /Gy"^
 -D CMAKE_CXX_COMPILER=cl^
 -D CMAKE_CXX_FLAGS="/GS- /Oy /Gw /Gy"^
 -D CMAKE_MT=mt^
 -D CMAKE_INSTALL_PREFIX=%SW_XML2_INSTALL_DIR%^
 -G Ninja^
 -S %SW_XML2_SOURCES_DIR%^
 -D LIBXML2_WITH_ICONV=NO^
 -D LIBXML2_WITH_ICU=NO^
 -D LIBXML2_WITH_LZMA=NO^
 -D LIBXML2_WITH_PYTHON=NO^
 -D LIBXML2_WITH_TESTS=NO^
 -D LIBXML2_WITH_THREADS=YES^
 -D LIBXML2_WITH_ZLIB=NO
