cmake^
 -G Ninja^
 -S %SW_SOURCES_PATH%\swift-corelibs-libdispatch^
 -B %SW_BINARIES_PATH%\libdispatch^
 -C %GITHUB_WORKSPACE%\cmake\caches\windows-x86_64-clang.cmake^
 -D SWIFT_STDLIB_DIR=%SW_BINARIES_PATH%\swift-stdlib^
 -C %GITHUB_WORKSPACE%\cmake\caches\windows-x86_64-swift-flags.cmake^
 -D CMAKE_BUILD_TYPE=Release^
 -D CMAKE_INSTALL_PREFIX=%SW_INSTALL_PATH%^
 -D BUILD_TESTING=NO^
 -D ENABLE_SWIFT=YES
