cmake^
 -G Ninja^
 -S %SW_SOURCES_PATH%\swift^
 -B %SW_BINARIES_PATH%\swift-stdlib^
 -C %GITHUB_WORKSPACE%\cmake\caches\windows-x86_64-clang.cmake^
 -C %GITHUB_WORKSPACE%\cmake\caches\swift-stdlib-windows-x86_64.cmake^
 -D CMAKE_BUILD_TYPE=Release^
 -D LLVM_DIR=%SW_BINARIES_PATH%\llvm\lib\cmake\llvm^
 -D SWIFT_NATIVE_SWIFT_TOOLS_PATH=%SW_TOOLCHAIN_PATH%\usr\bin^
 -D CMAKE_INSTALL_PREFIX=%SW_INSTALL_PATH%^
 -D SWIFT_WINDOWS_x86_64_ICU_UC_INCLUDE=%SW_ICU_PATH%\usr\include\unicode^
 -D SWIFT_WINDOWS_x86_64_ICU_UC=%SW_ICU_PATH%\usr\lib\icuuc%SW_ICU_VERSION%.lib^
 -D SWIFT_WINDOWS_x86_64_ICU_I18N_INCLUDE=%SW_ICU_PATH%\usr\include^
 -D SWIFT_WINDOWS_x86_64_ICU_I18N=%SW_ICU_PATH%\usr\lib\icuin%SW_ICU_VERSION%.lib^
 -D PYTHON_EXECUTABLE=%pythonLocation%\python.exe
