setlocal enabledelayedexpansion

if "%SW_LIMITED_RESOURCES%"=="YES" (
  set SW_ADDITIONAL_OPTIONS=-D LLVM_PARALLEL_LINK_JOBS=2 -D SWIFT_PARALLEL_LINK_JOBS=2
)

cmake^
 -B %SW_TOOLCHAIN_BUILD_DIR%^
 -C %SW_SWIFT_SOURCES_DIR%/cmake/caches/Windows-x86_64.cmake^
 -D CMAKE_BUILD_TYPE=Release^
 -D CMAKE_C_COMPILER=cl^
 -D CMAKE_C_FLAGS="/GS- /Oy /Gw /Gy"^
 -D CMAKE_CXX_COMPILER=cl^
 -D CMAKE_CXX_FLAGS="/GS- /Oy /Gw /Gy"^
 -D CMAKE_MT=mt^
 -D CMAKE_INSTALL_PREFIX=%SW_TOOLCHAIN_INSTALL_DIR%^
 -G Ninja^
 -S %SW_LLVM_PROJECT_SOURCES_DIR%/llvm^
 -D PACKAGE_VENDOR=Readdle^
 -D CLANG_VENDOR=Readdle^
 -D CLANG_VENDOR_UTI=com.readdle.clang^
 -D SWIFT_VENDOR=Readdle^
 -D LLVM_APPEND_VC_REV=NO^
 -D LLVM_VERSION_SUFFIX=""^
 -D LLDB_PYTHON_RELATIVE_PATH=lib/site-packages^
 -D SWIFT_ENABLE_EXPERIMENTAL_CONCURRENCY=YES^
 -D SWIFT_ENABLE_EXPERIMENTAL_DISTRIBUTED=YES^
 -D SWIFT_ENABLE_EXPERIMENTAL_DIFFERENTIABLE_PROGRAMMING=YES^
 -D SWIFT_ENABLE_EXPERIMENTAL_STRING_PROCESSING=YES^
 -D LLVM_EXTERNAL_CMARK_SOURCE_DIR=%SW_CMARK_SOURCES_DIR%^
 -D LLVM_EXTERNAL_SWIFT_SOURCE_DIR=%SW_SWIFT_SOURCES_DIR%^
 -D SWIFT_PATH_TO_LIBDISPATCH_SOURCE=%SW_DISPATCH_SOURCES_DIR%^
 -D EXPERIMENTAL_STRING_PROCESSING_SOURCE_DIR=%SW_SWIFT_EXPERIMENTAL_STRING_PROCESSING_SOURCES_DIR%^
 -D LLVM_USE_HOST_TOOLS=NO^
 -D LLVM_TABLEGEN=%SW_LLVM_TABLEGEN%^
 -D CLANG_TABLEGEN=%SW_CLANG_TABLEGEN%^
 -D LLDB_TABLEGEN=%SW_LLDB_TABLEGEN%^
 -D LLVM_CONFIG_PATH=%SW_LLVM_CONFIG%^
 -D SWIFT_NATIVE_SWIFT_TOOLS_PATH=%SW_LLVM_TOOLS_DIR%^
 -D SWIFT_BUILD_DYNAMIC_STDLIB=NO^
 -D SWIFT_BUILD_DYNAMIC_SDK_OVERLAY=NO^
 -D SWIFT_PATH_TO_SWIFT_SYNTAX_SOURCE=%SW_SWIFT_SYNTAX_SOURCES_DIR%^
 -D Python3_ROOT_DIR=$(PYTHON_ROOT)^
 -D Python3_INCLUDE_DIR=$(PYTHON_ROOT)/include^
 -D Python3_LIBRARY=$(PYTHON_ROOT)/libs/python310.lib^
 -D LLDB_PYTHON_EXE_RELATIVE_PATH=python.exe^
 -D LLDB_PYTHON_EXT_SUFFIX=.pyd^
 %SW_ADDITIONAL_OPTIONS%

endlocal
