%SW_LOG_JOB_INFO% --message="Configuring zlib..."

cmake^
 -B %SW_ZLIB_BUILD_DIR%^
 -D BUILD_SHARED_LIBS=NO^
 -D BUILD_TESTING=NO^
 -D CMAKE_BUILD_TYPE=Release^
 -D CMAKE_C_COMPILER=cl^
 -D CMAKE_C_FLAGS="/GS- /Oy /Gw /Gy"^
 -D CMAKE_CXX_COMPILER=cl^
 -D CMAKE_CXX_FLAGS="/GS- /Oy /Gw Gy"^
 -D CMAKE_MT=mt^
 -D CMAKE_INSTALL_PREFIX=%SW_ZLIB_INSTALL_DIR%^
 -G Ninja^
 -S %SW_ZLIB_SOURCES_DIR%^
 -D SKIP_INSTALL_FILES=YES
