cmake^
 -G Ninja^
 -S %SW_ZLIB_SOURCES_DIR%^
 -B %SW_ZLIB_BUILD_DIR%^
 -C %SW_WORKSPACE%\cmake\caches\windows-x86_64.cmake^
 -D CMAKE_BUILD_TYPE=MinSizeRel^
 -D CMAKE_INSTALL_PREFIX=%SW_ZLIB_INSTALL_DIR%^
 -D CMAKE_POSITION_INDEPENDENT_CODE=YES^
 -D BUILD_SHARED_LIBS=NO^
 -D BUILD_TESTING=NO
 