setlocal enabledelayedexpansion

%SW_PRE_STEP% --scope="sdk" --name="Install Module Maps" --flag=SW_SKIP_SDK_MODULES
if errorlevel 1 exit /b 0

set SW_SDK_INSTALL_SHARE_DIR=%SW_SDK_INSTALL_DIR%\share

set "SW_UCRT_MODULEMAP=ucrt.modulemap"
set "SW_VISUALC_MODULEMAR=visualc.modulemap"
set "SW_VISUALC_APINOTES=visualc.apinotes"
set "SW_WINSDK_MODULEMAP=winsdk.modulemap"

set "SW_SWIFT_SOURCES_PLATFORM_DIR=%SW_SWIFT_SOURCES_DIR%\stdlib\public\Platform"

set "SW_SOURCE_UCRT_MODULEMAP=%SW_SWIFT_SOURCES_PLATFORM_DIR%\%SW_UCRT_MODULEMAP%"
set "SW_SOURCE_VISUALC_MODULEMAR=%SW_SWIFT_SOURCES_PLATFORM_DIR%\%SW_VISUALC_MODULEMAR%"
set "SW_SOURCE_VISUALC_APINOTES=%SW_SWIFT_SOURCES_PLATFORM_DIR%\%SW_VISUALC_APINOTES%"
set "SW_SOURCE_WINSDK_MODULEMAP=%SW_SWIFT_SOURCES_PLATFORM_DIR%\%SW_WINSDK_MODULEMAP%"

set "SW_TARGET_UCRT_MODULEMAP=%SW_SDK_INSTALL_SHARE_DIR%\%SW_UCRT_MODULEMAP%"
set "SW_TARGET_VISUALC_MODULEMAR=%SW_SDK_INSTALL_SHARE_DIR%\%SW_VISUALC_MODULEMAR%"
set "SW_TARGET_VISUALC_APINOTES=%SW_SDK_INSTALL_SHARE_DIR%\%SW_VISUALC_APINOTES%"
set "SW_TARGET_WINSDK_MODULEMAP=%SW_SDK_INSTALL_SHARE_DIR%\%SW_WINSDK_MODULEMAP%"

if not exist %SW_SDK_INSTALL_SHARE_DIR% mkdir %SW_SDK_INSTALL_SHARE_DIR%

if exist "%SW_SOURCE_UCRT_MODULEMAP%" copy "%SW_SOURCE_UCRT_MODULEMAP%" "%SW_TARGET_UCRT_MODULEMAP%"
if exist "%SW_SOURCE_VISUALC_MODULEMAR%" copy "%SW_SOURCE_VISUALC_MODULEMAR%" "%SW_TARGET_VISUALC_MODULEMAR%"
if exist "%SW_SOURCE_VISUALC_APINOTES%" copy "%SW_SOURCE_VISUALC_APINOTES%" "%SW_TARGET_VISUALC_APINOTES%"
if exist "%SW_SOURCE_WINSDK_MODULEMAP%" copy "%SW_SOURCE_WINSDK_MODULEMAP%" "%SW_TARGET_WINSDK_MODULEMAP%"

exit /b 0

endlocal
