cmake^
 -G Ninja^
 -S %GITHUB_WORKSPACE%\zlib^
 -B %GITHUB_WORKSPACE%\b^
 -C %GITHUB_WORKSPACE%\cmake\caches\windows-x86_64.cmake^
 -D CMAKE_BUILD_TYPE=MinSizeRel^
 -D CMAKE_INSTALL_PREFIX=%SW_INSTALL_PATH%^
 -D CMAKE_POSITION_INDEPENDENT_CODE=YES^
 -D BUILD_SHARED_LIBS=NO^
 -D BUILD_TESTING=NO
 