name: build-script
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to fetch'     
        required: false
      branch_spec:
        description: 'Branch specification (main, 5.5, 5.4, 5.3)'
        required: true
        default: 'main'
      runs_on:
        description: 'Runner label (windows-latest, self-hosted)'
        required: true
        default: 'windows-latest'
      check_run_id:
        description: Check Run ID
        required: false

jobs:

  check-in:
    name: Check In
    runs-on: ubuntu-latest
    if: github.event.inputs.check_run_id

    steps:  
      - name: Get Current Run
        id: get_run
        run: |
          set -e
          
          http_code=$(curl -s -o run.json -w "%{http_code}" -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }})
      
          if [ "$http_code" != "200" ]; then
            echo "::error::Failed to fetch run ${{ github.run_id }}"
            exit 1
          fi
          
          HTML_URL=$(jq -r '.html_url' run.json)
          
          echo "Run HTML URL: $HTML_URL"          
          echo "::set-output name=html_url::$HTML_URL"

      - name: Update CI Check
        env:
          CHECK_RUN_ID: ${{ github.event.inputs.check_run_id }}
        run: |
          set -e
          
          http_code=$(curl -s -o check.json -w "%{http_code}" -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            -X PATCH https://api.github.com/repos/${{ github.repository }}/check-runs/$CHECK_RUN_ID \
            -d '{"status":"in_progress","details_url":"${{ steps.get_run.outputs.html_url }}"}')
          
          echo $http_code
          if [ "$http_code" != "200" ]; then
            echo "::error::Failed to update check run"
            exit 1
          fi

  build-script:
    name: Check Build Script
    runs-on: ${{ matrix.runs_on }}
    needs: [check-in]
    if: cancelled() == false
    defaults:
      run:
        shell: cmd
    strategy:
      fail-fast: false
      matrix:
        branch: ['${{ github.event.inputs.branch_spec }}']
        spec: [apple, readdle]
        runs_on: ['${{ github.event.inputs.runs_on }}']
        include:
          - spec: apple
            enable-no-objc-patch: NO
            runtime-patch-enabled: NO
          - spec: readdle
            enable-no-objc-patch: YES
            runtime-patch-enabled: YES

    steps:
      - name: Clean Workspace
        if: github.event.inputs.runs_on == 'self-hosted'
        run: |
          for /d %%d in (${{ github.workspace }}\*.*) do rmdir /s /q "%%d"
          del /f /q /s ${{ github.workspace }}

      - name: Checkout 
        uses: actions/checkout@v2

      - name: Select Python Version
        id: select-python-version
        run: |
          if "${{ matrix.branch }}"=="5.3" (
            echo ::set-output name=python-version::2.7.x
            echo SW_PYTHON_DIR=C:\Python27>>%GITHUB_ENV%
          ) else (
            echo ::set-output name=python-version::3.x.x
            echo SW_PYTHON_DIR="C:\Program Files\Python39">>%GITHUB_ENV%
          )

      - name: Setup Python ${{ steps.select-python-version.outputs.python-version }}
        if: github.event.inputs.runs_on != 'self-hosted'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ steps.select-python-version.outputs.python-version }}

      - name: Export Python Path
        if: github.event.inputs.runs_on != 'self-hosted'
        run: |
          echo SW_PYTHON_DIR="%pythonLocation%">>%GITHUB_ENV%

      - name: Get CMake 3.21.3
        if: github.event.inputs.runs_on != 'self-hosted' && matrix.branch != '5.3' && matrix.branch != '5.4'
        run: |
          choco install cmake --version=3.21.3

      - name: Get CMake 3.19.8
        if: github.event.inputs.runs_on != 'self-hosted' && (matrix.branch == '5.3' || matrix.branch == '5.4')
        run: |
          choco install cmake --version=3.19.8

      - name: Configure
        run: |
          subst

          scripts\configure.cmd^
           --interactive=NO^
           --branch ${{ matrix.branch }}^
           --sources-dir %GITHUB_WORKSPACE%\s^
           --build-dir %GITHUB_WORKSPACE%\b^
           --python-dir=%SW_PYTHON_DIR%^
           --install-dir %GITHUB_WORKSPACE%\i^
           --skip-toolchain-swift-test=YES^
           --skip-sdk-dispatch-test=YES^
           --skip-sdk-foundation-test=YES^
           --enable-no-objc-patch=${{ matrix.enable-no-objc-patch}}^
           --enable-print-patch=${{ matrix.runtime-patch-enabled }}^
           --sdk=${{ matrix.spec }}^
           --git-tag=${{ github.event.inputs.tag }}

      - name: Build
        run: |
          if "${{ matrix.branch }}"=="5.3" set SW_VC_VERSION=14.28.29910
          scripts\build.cmd

  check-out:
    name: Check Out
    runs-on: ubuntu-latest
    if: always()
    needs: [check-in, build-script]

    steps:
      - name: Update CI Check - Success
        if: github.event.inputs.check_run_id && needs.curl.result == 'success'
        env:
          CHECK_RUN_ID: ${{ github.event.inputs.check_run_id }}
        run: |
          set -e
          
          http_code=$(curl -s -o check.json -w "%{http_code}" -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            -X PATCH https://api.github.com/repos/${{ github.repository }}/check-runs/$CHECK_RUN_ID \
            -d '{"conclusion":"success"}')
          
          echo $http_code
          if [ "$http_code" != "200" ]; then
            echo "::error::Failed to update check run"
            exit 1
          fi

      - name: Update CI Check - Failure
        if: github.event.inputs.check_run_id && contains(needs.*.result, 'failure')
        env:
          CHECK_RUN_ID: ${{ github.event.inputs.check_run_id }}
        run: |
          set -e
          
          http_code=$(curl -s -o check.json -w "%{http_code}" -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            -X PATCH https://api.github.com/repos/${{ github.repository }}/check-runs/$CHECK_RUN_ID \
            -d '{"conclusion":"failure"}')
          
          echo $http_code
          if [ "$http_code" != "200" ]; then
            echo "::error::Failed to update check run"
            exit 1
          fi

      - name: Update CI Check - Cancelled
        if: github.event.inputs.check_run_id && contains(needs.*.result, 'cancelled')
        env:
          CHECK_RUN_ID: ${{ github.event.inputs.check_run_id }}
        run: |
          set -e
          
          http_code=$(curl -s -o check.json -w "%{http_code}" -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            -X PATCH https://api.github.com/repos/${{ github.repository }}/check-runs/$CHECK_RUN_ID \
            -d '{"conclusion":"cancelled"}')
          
          echo $http_code
          if [ "$http_code" != "200" ]; then
            echo "::error::Failed to update check run"
            exit 1
          fi

      - name: Update Badge - Success
        uses: schneegans/dynamic-badges-action@v1.0.0
        if: github.ref == 'refs/heads/master' && needs.build-script.result == 'success'
        with:
          auth: ${{ secrets.GISTS_TOKEN }}
          gistID: e75dcdc92f031e71745ff1dbb56decd4
          filename: ${{ github.workflow }}-${{ github.event.inputs.branch_spec }}-badge.json
          label: ${{ github.workflow }}-${{ github.event.inputs.branch_spec }}
          message: success
          color: success

      - name: Update Badge - Failure
        uses: schneegans/dynamic-badges-action@v1.0.0
        if: github.ref == 'refs/heads/master' && contains(needs.*.result, 'failure')
        with:
          auth: ${{ secrets.GISTS_TOKEN }}
          gistID: e75dcdc92f031e71745ff1dbb56decd4
          filename: ${{ github.workflow }}-${{ github.event.inputs.branch_spec }}-badge.json
          label: ${{ github.workflow }}-${{ github.event.inputs.branch_spec }}
          message: failure
          color: critical
